version: "3.8"

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nest-clean
    volumes:
      - ./data/pg:/data/postgres
